// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "TEST REST API": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=design
// --out=$(GOPATH)/src
// --version=v1.3.0

package app
