###########################################
### This is for building a docker image ###
### from a golang 1.9 base image        ###
### installing the goa and the goagen   ###
###########################################
From golang:1.9

ENV http_proxy http://www-proxy.ericsson.se:8080

RUN git config --global http.proxy $http_proxy && go get -u github.com/goadesign/goa/...

#CMD ["bash", "-c", "go get -u github.com/goadesign/goa/..."]

