###########################################
### This is for building a docker image ###
### from a centos base image            ###
### installing the golang environment   ###
###########################################
